
#baner config
banner: 
  location: cfg/banner.txt


# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8080

spring:
    # 环境 dev|test|demo|pro
    profiles:
        active: @profileActive@
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    # 指定静态资源的路径
    resources:
        static-locations: classpath:/static/,classpath:/views/,classpath:/META-INF/resources/
    redis:
        open: false  # 是否开启redis缓存  true开启   false关闭
        database: 0
        host: 10.211.55.5
        port: 6379
        password: Frank      # 密码（默认为空）
        timeout: 6000         # 连接超时时长（毫秒）
        pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10      # 连接池中的最大空闲连接
            min-idle: 5       # 连接池中的最小空闲连接

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation:  classpath:cfg/mybatis.xml

# 日志配置
logging:
  path: logs/
  config: classpath:cfg/logback-spring.xml


